'use strict';

// tests for postReviewV1
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('postReviewV1', '/src/handler.js', 'postReviewV1');

describe('postReviewV1', () => {
  let reviewPostData;

  before((done) => {
  	reviewPostData = {
  		'product-id': 'xxxxxx',
  		'user-name': 'Test Review Data',
  		'user-email': 'testreviewer@gmail.com',
  		'user-location': 'Evansville, IN',
  		'review-summary': 'Great product!',
  		'review-body': 'Test review',
  		'product-rating': 5,
  		'brand-recommendation-reason': 'Test brand recommendation reason',
  		'brand-recommendation-rating': 10,
  		'improves-game-rating': 5,
  		'quality-rating': 5,
  		'value-rating': 5,
  		'would-recommend': 'true',
  		'user-age': '7',
  		'user-gender': '2',
  		'user-description': '5',
  		'length-owned': '4'
  	}
    done();
  });

  it('postReviewV1', () => {
    return wrapped.run({body: reviewPostData}).then((response) => {
      expect(response).to.not.be.empty;
    });
  });
});
