service: serverless-aws-boilerplate

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  stage: ${opt:stage, 'development'}
  environment:
    NODE_ENV: ${opt:stage, 'development'}

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: handler
          method: post
          cors: true

package:
  individually: true
  include:
    - env.js.enc
    - envdotjs-key

plugins:
  - serverless-plugin-optimize
  - serverless-mocha-plugin