service: serverless-aws-boilerplate

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  stage: ${opt:stage, 'development'}
  environment:
    NODE_ENV: ${opt:stage, 'development'}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: handler
          method: post
          cors: true

package:
  individually: true
  include:
    - .env*

custom:
  optimize:
    presets: ['latest']
    plugins: ['transform-object-rest-spread']

plugins:
  - serverless-plugin-optimize
  - serverless-mocha-plugin