service: goalrilla-reviews-api

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  stage: ${opt:stage, 'development'}
  environment:
    NODE_ENV: ${opt:stage, 'development'}
    ENVDOTJS_KEY: ${env:ENVDOTJS_KEY}

functions:
  postReviewV1:
    handler: src/handler.postReviewV1
    events:
      - http:
          path: reviews
          method: post
          cors: true

package:
  individually: true
  include:
    - env.js.enc
    - envdotjs-key

plugins:
  - serverless-plugin-optimize
  - serverless-mocha-plugin